version: '3.4'

services:
  verticalsliceapi:
    image: ${DOCKER_REGISTRY-}verticalsliceapi
    build:
      context: API
      dockerfile: Dockerfile
  logger:
    image: datalust/seq:latest
    ports:
      - "5341:5341"
      - "8081:80"
    environment:
      ACCEPT_EULA: Y

